### ISSUE TITLE
Markdowns missing? Lack of convenience is caused... 

### ISSUE THREAD

**Issue by pixincreate** [msoultanidis/quillnote#50] opened 2021-07-05 06:18 UTC
Many Markdowns doesn't exist.   
Especially, for making task list. I'm aware that there's an option to do task lists but it's not convenient.
Lemme explain.     
Basically, what the task list option does is this:    
# Title.     
- [ ] Note 1
- [ ] Note 2
- [ ] and so on..
______
______
But, my user case is something like this:.   
# Title.    
## sub-title + to-do:
- [ ] something note 1
- [ ] something note 2
- [ ] and so on and so forth...
______
## another sub-title under same category or similar:
- [ ] Note 1
- [ ] now 2
- [ ] and so on...

**Comment by msoultanidis** [comment] 2021-07-05 06:38
Duplicate of https://github.com/msoultanidis/quillnote/issues/5

**Comment by pixincreate** [comment] 2021-07-05 07:06
![20210705_123429](https://user-images.githubusercontent.com/69745008/124431052-89fb3100-dd8d-11eb-84be-c7c19352be52.jpg)
This is what I meant actually....     
I don't think it is a duplicate of #5

**Comment by pixincreate** [comment] 2021-07-05 07:26
And yes, you cannot create a task list using Markdowns.

**Comment by msoultanidis** [comment] 2021-07-05 08:51
#5 is about having the ability to add both text content (titles, subtitles, whatever) and Quillnote task lists to a note which fits your use case.

Now about markdown task lists, they could be added to the app but they won't support features such as reordering which Quillnote's task lists support.

**Comment by pixincreate** [comment] 2021-07-05 09:07
> #5 is about having the ability to add both text content (titles, subtitles, whatever) and Quillnote task lists to a note which fits your use case.

Ok, I'm looking for this option as well. Coming from Nextcloud Notes, a user have flexibility to customize as you said above.


> Now about markdown task lists, they could be added to the app but they won't support features such as reordering which Quillnote's task lists support.     

Yea, I can understand. If you allow users to work with both task lists and text content, then this **might** not be a necessary option(unless practically checked) as both of them does the same job, but one with a draw back.

**Comment by msoultanidis** [comment] 2021-07-05 16:25
Added basic support for markdown task lists in https://github.com/msoultanidis/quillnote/commit/988190e7132d12454e2747ff3d4a9db1074c812d. They are now displayed correctly and you can check/uncheck a line with a new editor shortcut.

**Closed by msoultanidis** 2021-07-05 16:25 UTC
Labels: enhancement

**Comment by pixincreate** [comment] 2021-07-05 16:37
Thank you
