### ISSUE TITLE
Can't synchronize with nextcloud without https

### ISSUE THREAD

**Issue by KhazAkar** [msoultanidis/quillnote#38] opened 2021-07-03 05:36 UTC
Hi,
I wanted to use my local instance of Nextcloud, but this app does not allow to use server without https.
![Screenshot_20210703-073243_Quillnote](https://user-images.githubusercontent.com/12693890/124344181-2c21ea00-dbd1-11eb-824f-f38c2bfcf3f2.png)
I know that I should make use of https even in hone server instance without access from outside network, but support for http servers will be great.

**Comment by msoultanidis** [comment] 2021-07-03 07:04
Duplicate of https://github.com/msoultanidis/quillnote/issues/17

**Closed by msoultanidis** 2021-07-03 07:04 UTC
