### ISSUE TITLE
Add option to export each note to a separate .md file

### ISSUE THREAD

**Issue by sbstn87** [msoultanidis/quillnote#47] opened 2021-07-04 15:16 UTC
Hi,

is it possible to add an option to export each note to a separate .md file and a whole notebook to a set of .md files (perhaps zipped) for use in another markdown editor?

**Comment by msoultanidis** [comment] 2021-07-04 15:18
Duplicate of https://github.com/msoultanidis/quillnote/issues/9

**Closed by msoultanidis** 2021-07-04 15:18 UTC
Labels: duplicate, enhancement
