### ISSUE TITLE
Import repo or local directory with .md files

### ISSUE THREAD

**Issue by agichim** [msoultanidis/quillnote#112] opened 2021-08-18 10:25 UTC
## Repo

I moved away from Google Keep because the notes are basically isolated. I'm keeping all my notes in a directory with markdown files. I love the the Keep app but I moved away from Google altogether. Currently I'm using the free version of GitJournal and I imported my .md files repo and use that to push and pull on my phone and do the same with VSCodium.

Quillnote is absolutely beautiful but I don't want to let go of the system I have now and it's to much hassle to take notes in a separate app and then move them to my repo.

## Local directory

Probably this would be easiest to implement, a feature that allows you to import/open/use an existing local directory on your phone. The notes would be saved automatically and I wouldn't mind opening GitJournal to push the changes.

**Comment by msoultanidis** [comment] 2021-08-24 20:09
Duplicate of https://github.com/msoultanidis/quillnote/issues/9
This feature is implemented and currently is under testing. Expect it in the next update!

**Closed by msoultanidis** 2021-08-24 20:09 UTC
