### ISSUE TITLE
Option to show pending list item at top for lists

### ISSUE THREAD

**Issue by ChaudhariSumit** [msoultanidis/quillnote#118] opened 2021-08-23 13:23 UTC
In lists note, pending list items to be above the completed list items.

It can be done for main notes list and/or in single note.

It can be a togglable option in settings,
default sort or pending at top (or similar description)

**Comment by msoultanidis** [comment] 2021-08-24 20:04
Duplicate of https://github.com/msoultanidis/quillnote/issues/114

**Closed by msoultanidis** 2021-08-24 20:04 UTC
